### ISSUE TITLE
Upon clicking on a waypoint in the waypoint menu, MC 1.20 crashes.

### ISSUE THREAD

**Issue by GT3CH1** [GT3CH1/minecraft-mod#70]
**Describe the bug**
Upon attempting to edit a waypoint, the game crashes.

**To Reproduce**

1. Open up the waypoint settings dropdown
2. Click on a waypoint
3. Crash happens

**Expected behavior**
No Crash

**Screenshots/Video**

**Version Info (please complete the following information):**

- OS: Win 10
- Version: 1.4.4, MC1.20

**Additional context**
```
Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property colorCycle has not been initialized
	at com.peasenet.gui.mod.waypoint.GuiWaypoint.<init>(GuiWaypoint.kt:202)
	at com.peasenet.mods.render.ModWaypoint$createWaypoint$1.invoke(ModWaypoint.kt:104)
	at com.peasenet.mods.render.ModWaypoint$createWaypoint$1.invoke(ModWaypoint.kt:103)
	at com.peasenet.settings.Setting$setCallback$1.callback(Setting.kt:74)
	at com.peasenet.settings.Setting.onClick(Setting.kt:51)
	at com.peasenet.gavui.GuiToggle.mouseClicked(GuiToggle.java:114)
	at com.peasenet.gavui.GuiScroll.clickedOnChild(GuiScroll.java:392)
	at com.peasenet.gavui.GuiScroll.mouseClicked(GuiScroll.java:323)
	at com.peasenet.gui.GuiElement.method_25402(GuiElement.kt:91)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	... 16 more
```

**Comment by GT3CH1** [comment]
Fix has been implemented, closing.
